language: python
python:
  #TODO: Add more versions to grid (including Py2.7 which requires use of six probably)
  #TODO: Like above (just testing travis :-)
  - "3.5"

install: "pip install -r requirements/test.py"

script: python setup.py test