service: meme-generator

custom:
  bucket: meme123  #must be aws wide unique

provider:
  name: aws
  runtime: python2.7
  region: ap-southeast-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: "arn:aws:s3:::${self:custom.bucket}"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource: "arn:aws:s3:::${self:custom.bucket}"

functions:
  meme:
    handler: handler.meme_handler
    environment:
      bucket: ${self:custom.bucket}
    events:
      - http:
          path: ${self:service}
          method: POST

resources:
  Resources:
    MemeBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
